site_name: My Docs

# readthedocs
theme:  material
use_directory_urls: false

docs_dir: 'docs'



# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/hightfly01/mktest'


# Copyright
copyright: 'Copyright (c) 2018 farwmarth'


extra:
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  author:
    github: 'hightfly01'


# Extensions
markdown_extensions:
  #高亮
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
