site_name: My Docs

# readthedocs
theme:  material
use_directory_urls: false

docs_dir: 'docs'


pages:
- Home: 'index.md'
- 数据结构与算法:
    - '排序算法介绍': 'data_algorithms/index.md'
- c++基础:
    - 'c++环境搭建(Win)': 'cplus/cplus_win.md'



# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/hightfly01/mktest'


# Copyright
copyright: 'Copyright (c) 2018 farwmarth'


extra:
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  author:
    github: 'hightfly01'


# Extensions
markdown_extensions:
  #高亮
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
